version: '3.3'
services:
  backend:
    build: ./flask
    container_name: backend_kiosk_rot
    image: backend_kiosk_rot
    ports:
      - '5558:5558'
    volumes:
      - ./flask:/usr/src/app
      - /usr/src/app/__pycache__
      - /usr/src/app/uploads

  frontend:
    build: ./front
    container_name: frontend_kiosk_rot
    image: frontend_kiosk_rot
    ports:
      - '5557:5557'
    volumes:
      - ./front:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    stdin_open: true
    tty: true
    depends_on:
      - backend
    env_file:
      - ./front/.env

volumes:
  node_modules: {}

networks:
  default:
    name: shared_network
    driver: bridge